### ISSUE TITLE
please update the build instructions / scripts

### ISSUE THREAD

**Issue by felipesanches** [thundernixon/Libre-Caslon#6]
while trying to build the fonts that replicate the issue described at https://github.com/googlefonts/fontbakery/issues/2278 I noticed that the build instructions in this repo seem a bit out of sync with the repo contents. I tried to adapt the procedures by guessing which scripts I should run, but this resulted in some crashes such as these:

<img width="1280" alt="captura de tela 2019-01-16 as 02 08 09" src="https://user-images.githubusercontent.com/213676/51225849-b60f6700-1933-11e9-90f3-10fd658a88b2.png">

<img width="1280" alt="captura de tela 2019-01-16 as 02 08 32" src="https://user-images.githubusercontent.com/213676/51225871-d8a18000-1933-11e9-8508-179ad8cf8a07.png">

**Comment by thundernixon** [comment]
Thanks, @felipesanches, I'll update these ASAP! 

Marc helped to set up a simplified build script for this repo, but I think some wires got crossed when I merged the PR, so it's not quite working as expected yet. As soon as I debug it, I'll update the README. 

Until then, you can checkout [e0d74a1c6](https://github.com/thundernixon/Libre-Caslon/commit/e0d74a1c628b8086690f1869dc965b47fa8eda68), and it should have no issues building.

**Comment by felipesanches** [comment]
thanks! :-D

**Comment by thundernixon** [comment]
I've updated the build instructions. Please let me know if they are still causing problems.

Thanks!
